# Generated by Django 3.1.1 on 2020-11-21 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(default='default.jpg', upload_to='movies')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShowTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 24, 35, 586235))),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieTicketBooking.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='TickectCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieTicketBooking.showtiming')),
                ('total_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieTicketBooking.totalcount')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='theater_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieTicketBooking.theater'),
        ),
    ]
