# Generated by Django 3.1.1 on 2020-11-21 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTicketBooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcount',
            name='Tickets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MovieTicketBooking.showtiming'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtiming',
            name='showtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 46, 20, 166434)),
        ),
        migrations.DeleteModel(
            name='TickectCount',
        ),
    ]
